export const MessageType = {
    DISCOVER: "DISCOVER",
    DISCOVER_RESPONSE: "DISCOVER_RESPONSE",
    CONNECT_REQUEST: "CONNECT_REQUEST",
    CONNECT_ACCEPT: "CONNECT_ACCEPT",
    CONNECT_REJECT: "CONNECT_REJECT",
    SYNC_REQUEST: "SYNC_REQUEST",
    TRANSFER_START: "TRANSFER_START",
    CHUNK: "CHUNK",
    CHUNK_ACK: "CHUNK_ACK",
    VERIFY_REQUEST: "VERIFY_REQUEST",
    VERIFY_SUCCESS: "VERIFY_SUCCESS",
    TRANSFER_COMPLETE: "TRANSFER_COMPLETE",
    ERROR: "ERROR",
} as const;

export type MessageType =
    typeof MessageType[keyof typeof MessageType];